### PR TITLE
Python 3 Compatibility with tests OK

### PR DESCRIPTION
**Pull request by antoniojesvs**
WebHelpers2 (parsing list/tuple to list of Options in "select")

### CODE REVIEW

**Comment by lambacck** [comment]
This change will break every existing use of pyramid_simpleform.

**Comment by antoniojesvs** [comment]
Can you be more specific? I have run successfully the tests in both python 2.7 and 3.4.

**Comment by antoniojesvs** [comment]
Ok, I see that the options parser has to be more complex. Let me try to adapt the parser of webhelpers1 and add their example tests.

**Comment by antoniojesvs** [comment]
Now it uses the code from WebHelpers-1.3 to parse list/tuple to Options.
The order of the parameters to Option(value, label) has changed in webhelpers2 to Option(label, value), but I have inverted the order so its compatible with version 1.

Let me know if there are more problems

Maybe It would be a good idea to have two different versions, one for webhelpers1 and another one for webhelpers2. I would like to have at least Python3 compatibility in the official pyramid_simpleform.
What do you think?

**Comment by antoniojesvs** [comment]
I have implemented what you proposed in: https://github.com/Pylons/pyramid_simpleform/pull/18#issuecomment-102810699

I didn't like to change the order of params of webhelpers2 Options(), so now depends on the version. People using webhelpers1 (and Option obj's) that want to change to webhelpers2 will have to adapt their code.
People that don't want to change to webhelpers2 yet won't notice any change.
"options" in list/tuple format are also available using WebHelpers2.

What do you think?

**Pull request merged**
